### ISSUE TITLE
Bug: `Wrap Lines on Click` not work

### ISSUE THREAD

**Issue by magicdmer** [mayurankv/Obsidian-Code-Styler#82] opened 2023-08-14 02:02 UTC
## Describe the bug
After update to 1.0.5, `Wrap Lines on Click`  still not work , 1.0.3 main.js works well

### Environment
- Plugin Version: 1.0.5
- Obsidian Version:  1.3.7
- Platform:  Desktop
- OS:  Windows 11
- Theme:  blue topaz

Reference：#66

**Comment by mayurankv** [comment] 2023-08-15 12:00
I actually couldn't reproduce your issue. There was a small bug where setting `wrap` or `unwrap:false` would actually set it to wrap. I'm going to fix that in the coming release. Please let me know if the issue persists. If it does, please ensure that your global settings for line wrapping are what you expect as well as the codeblock parameters.

**Comment by magicdmer** [comment] 2023-08-16 06:46
I'm very confident that my settings are fine. When I replaced with main.js version 1.0.3 and restarted Obsidian, everything worked perfectly

**Comment by magicdmer** [comment] 2023-08-16 06:56
I conducted some tests and found that it may be related to the theme. When I use the `blue topaz` theme, the issue occurs, but when I switch to other themes like `minimal`, it works fine. However, one thing I can confirm is that when I switch to main.js version 1.0.3, it also worked well. Can you please take a look at this compatibility issue?

**Comment by mayurankv** [comment] 2023-08-16 07:51
Yeah of course! Always happy to make the plug-in more compatible with other themes/plugins. I'll have a look later today!

**Comment by mayurankv** [comment] 2023-08-16 07:52
It'll be an overriding important style in the css that's causing it as before I applied the style directly to element whereas now it is applied via classes. Shouldn't be a hard fix.

**Comment by mayurankv** [comment] 2023-08-16 08:29
This should be fixed in the next release.

**Closed by mayurankv** 2023-08-16 08:29 UTC
Labels: bug, future work, reading mode, needs repro
