### ISSUE TITLE
Bug: About set `wrap` something wrong

### ISSUE THREAD

**Issue by magicdmer** [mayurankv/Obsidian-Code-Styler#100] opened 2023-08-21 07:25 UTC
## Describe the bug
1.  enable `Unwrap codeblock lines`
2.  disable `Wrap lines on Click`
3.  we write code like follow:
\```c wrap
int main()
{
    return 0;
}
\```

The code wraps okay, but when I click on it to copy the text, it becomes unwrapped. It's wrong.

### Environment
- Plugin Version: 1.0.7
- Obsidian Version:  1.3.7
- Platform:  Desktop
- OS:  Windows 10
- Theme:  blue topaz

**Comment by mayurankv** [comment] 2023-08-21 07:32
That behaviour isn't intended yep. I'll try fix this with the next release. Thanks again!

**Comment by mayurankv** [comment] 2023-08-24 11:36
By the way, what are your wrap settings like in the settings? I mean the default wrap behaviour and also click to unwrap settings.

**Comment by mayurankv** [comment] 2023-08-24 11:37
Also sorry, how would that example codeblock wrap, it has got really short lines. Is that the codeblock you're having issues with?

**Comment by magicdmer** [comment] 2023-08-25 09:14
If I reverse the problematic settings and actions, then it works fine， like follow:

1. Disable `Unwrap codeblock lines`
2. Enable `Wrap lines on Click`
3. write code long line use  `unwrap`

when i click on it , it will not wrapped again

**Comment by mayurankv** [comment] 2023-08-25 12:10
Ah thank you! Sorry I missed that somehow. Will look into this.

**Comment by mayurankv** [comment] 2023-08-25 23:12
Ok, I've reproduced the issue, its yet another css quirk unfortunately. This will get fixed in the next release but that may not be for a little while as I'm going to be a bit busy. Shouldn't be too long at all though.

**Comment by mayurankv** [comment] 2023-08-27 08:14
Resolved for the next release.

**Closed by mayurankv** 2023-08-27 08:14 UTC
Labels: bug, future work, reading mode
