### ISSUE TITLE
Bug: CRASH with inline code in Source & Live Preview

### ISSUE THREAD

**Issue by qlassiqa** [mayurankv/Obsidian-Code-Styler#208] opened 2023-12-12 16:00 UTC
## Describe the bug
Trying to add the `{python}` language marker inside an existing inline code crashes Obsidian in both Source mode & Live Preview, with no console errors whatsoever.

### Steps to reproduce
1. Open a clean Obsidian sandbox vault with no snippets, themes or plugins, then install Code Styler
2. Type the following inline code **without** any language marker:
> `import pypy; print("code" + 'g' + aaa[23]); def bfs(): return None; False #test`
3. Try adding the `{python} ` marker at the start of that inline code, and as soon as you try to type `{` Obsidian will crash.

### Expected behaviour
Obsidian should not crash when specifying a language to an existing inline code.

### Current behaviour
Obsidian crashes as soon as I type the `{` bracket to add a language to an existing inline code.

### Environment
Code Styler 1.1.4
Obsidian 1.5.1
Platform: Desktop
OS: Windows 10
No theme, no CSS snippets, no other plugins.

**Comment by mayurankv** [comment] 2023-12-15 11:21
Woah this is really weird. Thanks so much for letting me know. I need to do some testing to solve this.

**Comment by mayurankv** [comment] 2023-12-15 11:24
I think I have an idea of how to solve this. For my reference, it appears the parsing is extremely slow and needs to be improved.

**Comment by qlassiqa** [comment] 2024-01-08 01:24
Yep, that's what I noticed, too, that parsing becomes extremely slow with each typed character to the point it freezes.

**Comment by MMongelli99** [comment] 2024-01-15 17:54
I'm experiencing the same issue. This line is causing the app to freeze and need to be quit:
`{zsh icon title:foo } $ bump2version {major|minor|patch} --allow-dirty`

It was displaying like this:
<img width="142" alt="code styler freeze bug" src="https://github.com/mayurankv/Obsidian-Code-Styler/assets/45768887/0c31917d-e3f5-4c91-9d71-92bdfa06d66d">

I figured the curly braces might be causing an issue. I tried removing them, but as soon as I tried to backspace the app would freeze again and need to be quit. I deleted the whole code snippet at once and replaced it with `{shell icon title:"bump version"} bump2version {major|minor|patch} --allow-dirty`, which is not causing Obsidian to freeze, but it does not display correctly:
<img width="221" alt="code styler display bug" src="https://github.com/mayurankv/Obsidian-Code-Styler/assets/45768887/66f78c14-c84e-402e-8f8e-2527341e3d19">

**Environment**
- Code Styler 1.1.4
- Version 1.5.3 (Installer 1.4.16)
- Desktop
- macOS Ventura 13.4.1

Cool plugin though, this is the first issue I've had with it

**Comment by mayurankv** [comment] 2024-01-23 14:58
Really sorry about this! My laptop actually broke over Christmas and I'm trying to sort a replacement right now so I haven't had a chance to take a proper look at this. Will definitely try and solve it as soon as I'm back up and running!

**Comment by h3retic** [comment] 2024-02-03 17:29
Want to add another example to this for what it is worth. I have created the below codeblock and if I attempt to modify it, say to change it to {powershell icon}, it immediately freezes the application and I have to close and re-open it:

![image](https://github.com/mayurankv/Obsidian-Code-Styler/assets/53059550/315bc582-fda4-47a9-8f37-a18be73633a5)

**Comment by mayurankv** [comment] 2024-02-04 13:55
Once again sorry, I know how frustrating bugs are. I'm currently very busy but I'll try and find some time to get this done in the next couple of weeks.

**Comment by SpreadZhao** [comment] 2024-02-13 12:51
> Once again sorry, I know how frustrating bugs are. I'm currently very busy but I'll try and find some time to get this done in the next couple of weeks.

I have encountered the same issue. My operating system is Ubuntu 22.04, and the Obsidian version is 1.5.3. When editing inline code in Live Preview mode, as soon as {some language} xxx is added, CPU usage instantly spikes to 100%. Sometimes, this directly leads to the program freezing, and even after a restart, my files become blank!

**Comment by xt0rted** [comment] 2024-02-17 21:01
I've been running into this for a few weeks and only just now realized it was this extension. What I've been able to figure out so far is it's the regex for parsing the inline code blocks. The change made in https://github.com/mayurankv/Obsidian-Code-Styler/commit/b59ea02fb3ff2be90a18f3e3590a8e7fd445f13c is when it starts and if you run both of those versions through [regex101.com](https://regex101.com) the original works but the modified one will give a warning saying:

> Your expression took too long to finish and was terminated. Please increase the timeout and try again.
>
> This may be an indication of catastrophic backtracking. To find out more and what this is, please read the following article: [Runaway Regular Expressions](http://www.regular-expressions.info/catastrophic.html)

**Comment by mayurankv** [comment] 2024-02-19 14:02
The specific breaking commit is super helpful!

**Comment by mayurankv** [comment] 2024-02-20 00:26
I'm just adding a list of all the example snippets that break:

- `{python} import pypy; print("code" + 'g' + aaa[23]); def bfs(): return None; False #test`
- `{zsh icon title:foo } $ bump2version {major|minor|patch} --allow-dirty`
- `{js icon title:foo} javascript:(function(){alert('你好')})()`

**Comment by xt0rted** [comment] 2024-02-20 01:27
Here's a stripped down version of the code block that was causing me issue with the new regex but not with the old one.

Flavor: ECMAScript
Function: Match
RegEx: `/^{( *(?:\w+(?: +(?:(?:[^\s"']+|"[^"]*"|'[^']*')+))*)? *)} *?([^ ].*?)$/m`
Test string:
```
{http icon} https://localhost/906e0c38-f877-46ef-8cd5-a21238aa743b
```

I thought I ran into a code block that didn't work with either, but all of the ones I'm testing look to be ok with the old regex so maybe it was a false positive due to a bad test setup at the time.

I patched the copy of the plugin in my vault to use the old regex and so far haven't had any issues with it locking up.

**Comment by mayurankv** [comment] 2024-02-20 01:44
I managed to reproduce the error. I've now simplified unnecessarily complicated regex to something that just matches whatever is inside the brackets unless there is an unescaped bracket (note brackets in quotes should work fine). I believe this should now be fixed and will be included in the next release. Currently working on another feature and will release as soon as that is done!

**Closed by mayurankv** 2024-02-20 01:44 UTC
Labels: bug, future work, editing mode, High Priority

**Comment by mayurankv** [comment] 2024-02-20 01:46
Just to note, I changed the regex initially because I aim to add some more inline parameters in the future which would get cumbersome with the old regex, the new fixed regex will allow that, I'll update this thread when I manage to create the new release!

**Comment by mayurankv** [comment] 2024-02-21 01:47
Released now!
