### ISSUE TITLE
Bug: Header background color

### ISSUE THREAD

**Issue by chilljalapeno** [mayurankv/Obsidian-Code-Styler#225] opened 2024-02-23 13:55 UTC
Header background color will not change to transparent even if it set to be transparent. I see the header background change as I change the language name. For Dart is blue for D is orange. I would like to know if I can have all the background header colors transparent.
### Steps to reproduce

````markdown
```dart title:Mircea
final something = 3;

```
````

### Environment

- Plugin Version: 
- Obsidian Version:  
- Platform:  
- OS:  
- Theme:  
- CSS Snippets:

**Comment by chilljalapeno** [comment] 2024-02-23 14:05
Even more weird is that the header is set fine in the preview and it looks alright but in the editing mode it has the background color. I will attach some images.

Reading mode
---
![Screenshot 2024-02-23 at 16 04 04](https://github.com/mayurankv/Obsidian-Code-Styler/assets/59742583/14659cd7-8e33-4fa1-bd24-8588f4f8c1f1)

Editing mode
---
![Screenshot 2024-02-23 at 16 05 10](https://github.com/mayurankv/Obsidian-Code-Styler/assets/59742583/64a74641-0556-4198-8059-722724b46a75)

**Comment by mayurankv** [comment] 2024-02-23 14:32
Thanks for the report, let me look into it! By transparent, what exactly do you want? The same colour as the main codeblock?

**Comment by mayurankv** [comment] 2024-02-23 14:37
Can you share your data.json from the `.obsidian/plugins/code-styler` folder?

**Comment by mayurankv** [comment] 2024-02-23 14:50
I've replicated what you mean. This occurs because of how the language borders need to be drawn in (live preview and reading mode are very very different in terms of the underlying structure so to make it cohesive is quite hard). The way to properly tackle this would be to set the colour to the same colour as the codeblock background. If this is transparent, then this would be equivalent to setting all the colours in the codeblock settings to the same as the background colour of your theme. There's not really a reason you would need to set it to be transparent separately unless:

- Your theme changes frequently and you want it to be updated independent of this plugins' settings
- You have some proper translucency/transparency in your theme that you want to show

If it is the first case, let me know and I'll have a think about how this can be done via settings ( it is already possible to set a css variable as the colour in the backend so potentially exposing that might be the solution). If you are in the second case, there is not necessarily an easy way to do this. I'd have to think about it quite hard (though it is again something I want to solve since I'm actually trying to get my Obsidian to have proper vibrancy). If its any other case I wouldn't think transparency is needed and an actual colour could just be set, but if I'm wrong please let me know!

**Comment by chilljalapeno** [comment] 2024-02-23 18:35
this is the data.json
{
  "themes": {
    "Default": {
      "settings": {
        "codeblock": {
          "lineNumbers": true,
          "unwrapLines": true,
          "wrapLinesActive": false,
          "curvature": 4
        },
        "gutter": {
          "highlight": true,
          "activeLine": false
        },
        "header": {
          "title": {
            "textFont": "",
            "textBold": false,
            "textItalic": true
          },
          "languageTag": {
            "display": "none",
            "textFont": "",
            "textBold": true,
            "textItalic": false
          },
          "languageIcon": {
            "display": "none",
            "displayColour": true
          },
          "externalReference": {
            "displayRepository": true,
            "displayVersion": true,
            "displayTimestamp": true
          },
          "fontSize": 14,
          "foldPlaceholder": ""
        },
        "highlights": {
          "activeCodeblockLine": false,
          "activeEditorLine": false
        },
        "inline": {
          "syntaxHighlight": true,
          "style": true,
          "fontWeight": 4,
          "curvature": 6,
          "paddingVertical": 5,
          "paddingHorizontal": 5,
          "marginHorizontal": 0,
          "titleFontWeight": 8
        },
        "advanced": {
          "gradientHighlights": false,
          "gradientHighlightsColourStop": "70%",
          "languageBorderColour": false,
          "languageBorderWidth": 5,
          "iconSize": 28
        }
      },
      "colours": {
        "light": {
          "codeblock": {
            "backgroundColour": "--code-background",
            "textColour": "--code-normal"
          },
          "gutter": {
            "backgroundColour": "--code-background",
            "textColour": "--text-faint",
            "activeTextColour": "--text-muted"
          },
          "header": {
            "backgroundColour": "--code-background",
            "title": {
              "textColour": "--code-comment"
            },
            "languageTag": {
              "backgroundColour": "--code-background",
              "textColour": "--code-comment"
            },
            "externalReference": {
              "displayRepositoryColour": "#00FFFF",
              "displayVersionColour": "#FF00FF",
              "displayTimestampColour": "#808080"
            },
            "lineColour": "--color-base-30"
          },
          "highlights": {
            "activeCodeblockLineColour": "--color-base-30",
            "activeEditorLineColour": "--color-base-20",
            "defaultColour": "--text-highlight-bg",
            "alternativeHighlights": {}
          },
          "inline": {
            "backgroundColour": "--code-background",
            "textColour": "--code-normal",
            "activeTextColour": "--code-normal",
            "titleTextColour": "--code-comment"
          },
          "advanced": {
            "buttonColour": "--text-muted",
            "buttonActiveColour": "--text-normal"
          }
        },
        "dark": {
          "codeblock": {
            "backgroundColour": "--code-background",
            "textColour": "--code-normal"
          },
          "gutter": {
            "backgroundColour": "--code-background",
            "textColour": "--text-faint",
            "activeTextColour": "--text-muted"
          },
          "header": {
            "backgroundColour": "--code-background",
            "title": {
              "textColour": "--code-comment"
            },
            "languageTag": {
              "backgroundColour": "--code-background",
              "textColour": "--code-comment"
            },
            "externalReference": {
              "displayRepositoryColour": "#00FFFF",
              "displayVersionColour": "#FF00FF",
              "displayTimestampColour": "#808080"
            },
            "lineColour": "--color-base-30"
          },
          "highlights": {
            "activeCodeblockLineColour": "--color-base-30",
            "activeEditorLineColour": "--color-base-20",
            "defaultColour": "--text-highlight-bg",
            "alternativeHighlights": {}
          },
          "inline": {
            "backgroundColour": "--code-background",
            "textColour": "--code-normal",
            "activeTextColour": "--code-normal",
            "titleTextColour": "--code-comment"
          },
          "advanced": {
            "buttonColour": "--text-muted",
            "buttonActiveColour": "--text-normal"
          }
        }
      }
    },
    "Solarized": {
      "settings": {
        "codeblock": {
          "lineNumbers": true,
          "unwrapLines": true,
          "wrapLinesActive": false,
          "curvature": 4
        },
        "gutter": {
          "highlight": true,
          "activeLine": false
        },
        "header": {
          "title": {
            "textFont": "",
            "textBold": false,
            "textItalic": true
          },
          "languageTag": {
            "display": "none",
            "textFont": "",
            "textBold": true,
            "textItalic": false
          },
          "languageIcon": {
            "display": "none",
            "displayColour": true
          },
          "externalReference": {
            "displayRepository": true,
            "displayVersion": true,
            "displayTimestamp": true
          },
          "fontSize": 14,
          "foldPlaceholder": ""
        },
        "highlights": {
          "activeCodeblockLine": false,
          "activeEditorLine": false
        },
        "inline": {
          "syntaxHighlight": true,
          "style": true,
          "fontWeight": 4,
          "curvature": 6,
          "paddingVertical": 5,
          "paddingHorizontal": 5,
          "marginHorizontal": 0,
          "titleFontWeight": 8
        },
        "advanced": {
          "gradientHighlights": false,
          "gradientHighlightsColourStop": "70%",
          "languageBorderColour": false,
          "languageBorderWidth": 5,
          "iconSize": 28
        }
      },
      "colours": {
        "light": {
          "codeblock": {
            "backgroundColour": "#fdf6e3",
            "textColour": "#bababa"
          },
          "gutter": {
            "backgroundColour": "#eee8d5",
            "textColour": "#6c6c6c",
            "activeTextColour": "#8c8c8c"
          },
          "header": {
            "backgroundColour": "#D5CCB4",
            "title": {
              "textColour": "#866704"
            },
            "languageTag": {
              "backgroundColour": "#B8B5AA",
              "textColour": "#C25F30"
            },
            "externalReference": {
              "displayRepositoryColour": "#941100",
              "displayVersionColour": "#ff9300",
              "displayTimestampColour": "#808080"
            },
            "lineColour": "#EDD489"
          },
          "highlights": {
            "activeCodeblockLineColour": "#eee8d5",
            "activeEditorLineColour": "#60460633",
            "defaultColour": "#E9DFBA",
            "alternativeHighlights": {}
          },
          "inline": {
            "backgroundColour": "#fdf6e3",
            "textColour": "#bababa",
            "activeTextColour": "#bababa",
            "titleTextColour": "#C25F30"
          },
          "advanced": {
            "buttonColour": "--text-muted",
            "buttonActiveColour": "--text-normal"
          }
        },
        "dark": {
          "codeblock": {
            "backgroundColour": "#002b36",
            "textColour": "#bababa"
          },
          "gutter": {
            "backgroundColour": "#073642",
            "textColour": "#6c6c6c",
            "activeTextColour": "#4c4c4c"
          },
          "header": {
            "backgroundColour": "#0a4554",
            "title": {
              "textColour": "#dadada"
            },
            "languageTag": {
              "backgroundColour": "#008080",
              "textColour": "#000000"
            },
            "externalReference": {
              "displayRepositoryColour": "#00FFFF",
              "displayVersionColour": "#9437ff",
              "displayTimestampColour": "#808080"
            },
            "lineColour": "#46cced"
          },
          "highlights": {
            "activeCodeblockLineColour": "#073642",
            "activeEditorLineColour": "#468eeb33",
            "defaultColour": "#054b5c",
            "alternativeHighlights": {}
          },
          "inline": {
            "backgroundColour": "#002b36",
            "textColour": "#bababa",
            "activeTextColour": "#bababa",
            "titleTextColour": "#000000"
          },
          "advanced": {
            "buttonColour": "--text-muted",
            "buttonActiveColour": "--text-normal"
          }
        }
      }
    }
  },
  "selectedTheme": "Default",
  "currentTheme": {
    "settings": {
      "codeblock": {
        "lineNumbers": true,
        "unwrapLines": true,
        "wrapLinesActive": true,
        "curvature": 4
      },
      "gutter": {
        "highlight": true,
        "activeLine": false
      },
      "header": {
        "title": {
          "textFont": "",
          "textBold": false,
          "textItalic": false
        },
        "languageTag": {
          "display": "if_header_shown",
          "textFont": "",
          "textBold": false,
          "textItalic": false
        },
        "languageIcon": {
          "display": "if_header_shown",
          "displayColour": false
        },
        "externalReference": {
          "displayRepository": true,
          "displayVersion": true,
          "displayTimestamp": true
        },
        "fontSize": 14,
        "foldPlaceholder": ""
      },
      "highlights": {
        "activeCodeblockLine": false,
        "activeEditorLine": false
      },
      "inline": {
        "syntaxHighlight": true,
        "style": true,
        "fontWeight": 4,
        "curvature": 6,
        "paddingVertical": 5,
        "paddingHorizontal": 5,
        "marginHorizontal": 0,
        "titleFontWeight": 8
      },
      "advanced": {
        "gradientHighlights": false,
        "gradientHighlightsColourStop": "70%",
        "languageBorderColour": true,
        "languageBorderWidth": 5,
        "iconSize": 28
      }
    },
    "colours": {
      "light": {
        "codeblock": {
          "backgroundColour": "--code-background",
          "textColour": "--code-normal"
        },
        "gutter": {
          "backgroundColour": "--code-background",
          "textColour": "--text-faint",
          "activeTextColour": "--text-muted"
        },
        "header": {
          "backgroundColour": "#00000000",
          "title": {
            "textColour": "--code-comment"
          },
          "languageTag": {
            "backgroundColour": "#0A0A0A1A",
            "textColour": "--code-comment"
          },
          "externalReference": {
            "displayRepositoryColour": "#00FFFF",
            "displayVersionColour": "#FF00FF",
            "displayTimestampColour": "#808080"
          },
          "lineColour": "--color-base-30"
        },
        "highlights": {
          "activeCodeblockLineColour": "--color-base-30",
          "activeEditorLineColour": "--color-base-20",
          "defaultColour": "--text-highlight-bg",
          "alternativeHighlights": {}
        },
        "inline": {
          "backgroundColour": "--code-background",
          "textColour": "--code-normal",
          "activeTextColour": "--code-normal",
          "titleTextColour": "--code-comment"
        },
        "advanced": {
          "buttonColour": "--text-muted",
          "buttonActiveColour": "--text-normal"
        }
      },
      "dark": {
        "codeblock": {
          "backgroundColour": "--code-background",
          "textColour": "--code-normal"
        },
        "gutter": {
          "backgroundColour": "--code-background",
          "textColour": "--text-faint",
          "activeTextColour": "--text-muted"
        },
        "header": {
          "backgroundColour": "#00000000",
          "title": {
            "textColour": "--code-comment"
          },
          "languageTag": {
            "backgroundColour": "#0A0A0A1A",
            "textColour": "--code-comment"
          },
          "externalReference": {
            "displayRepositoryColour": "#00FFFF",
            "displayVersionColour": "#FF00FF",
            "displayTimestampColour": "#808080"
          },
          "lineColour": "--color-base-30"
        },
        "highlights": {
          "activeCodeblockLineColour": "--color-base-30",
          "activeEditorLineColour": "--color-base-20",
          "defaultColour": "--text-highlight-bg",
          "alternativeHighlights": {}
        },
        "inline": {
          "backgroundColour": "--code-background",
          "textColour": "--code-normal",
          "activeTextColour": "--code-normal",
          "titleTextColour": "--code-comment"
        },
        "advanced": {
          "buttonColour": "--text-muted",
          "buttonActiveColour": "--text-normal"
        }
      }
    }
  },
  "newTheme": "",
  "newHighlight": "",
  "exampleCodeblockParameters": "dart title:foo",
  "exampleCodeblockContent": "print(\"This line is very long and should be used as an example for how the plugin deals with wrapping and unwrapping very long lines given the choice of codeblock parameters and settings.\")\nprint(\"This line is highlighted.\")",
  "exampleInlineCode": "{python icon title:foo} print(\"This is inline code\")",
  "decoratePrint": true,
  "excludedLanguages": "ad-*, reference",
  "externalReferenceUpdateOnLoad": false,
  "processedCodeblocksWhitelist": "run-*, include",
  "redirectLanguages": {},
  "version": "1.1.7"
}

I wanted to say thank you for taking your time to respond to my request. I realize this is just a cosmetic and the plugin is good enough as it is. I do not yet understand your last message. I am using annuppuccin(with rose-pine) as my theme and want to achieve the same effect that I have in the reading mode in the editing mode, but if it is overly complicated or the plugin can not yet do that, it is not a problem. The plugin works great, the coding blocks look better than with any other plugin or default settings, so that go out of your way to change it if it is too complicated. Thank you so much for your work, I will continue to use it and enjoy it.

**Comment by mayurankv** [comment] 2024-02-23 18:46
No worries! If you switch themes, and switch back to the default theme, do you still get the annoying behaviour? Does the behaviour out of the box not work for you? I understand that you want the background and header to be transparent and thus the same colour as the editor, is that right? If so the easy way would be setting the colours to `#191724` for the anuppucin rose pine theme. Let me know if you need further help! (I'll close this for now as it's not a bug, but happy to continue helping).

**Closed by mayurankv** 2024-02-23 18:46 UTC
Labels: bug

**Comment by chilljalapeno** [comment] 2024-02-23 18:50
Worked like a charm, thank you 👍 looks way better now.
